### ISSUE TITLE
Support RSA-PSS keys in LoadSigner/Verifier

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore#1066]
**Description**

We support RSA-PSS keys - https://github.com/sigstore/sigstore/blob/main/pkg/signature/rsapss.go - but the LoadVerifier, LoadSigner, and LoadSignerVerifier functions listed below do not.

* https://github.com/sigstore/sigstore/blob/main/pkg/signature/verifier.go#L42
* https://github.com/sigstore/sigstore/blob/main/pkg/signature/signer.go#L61
* https://github.com/sigstore/sigstore/blob/main/pkg/signature/signerverifier.go#L41

**Comment by bobcallaway** [comment]
Do https://github.com/sigstore/sigstore/blob/8da2a8c9ce81b91324ceffe1fa22318de1ffad96/pkg/signature/rsapss.go#L217, https://github.com/sigstore/sigstore/blob/8da2a8c9ce81b91324ceffe1fa22318de1ffad96/pkg/signature/rsapss.go#L57 and https://github.com/sigstore/sigstore/blob/8da2a8c9ce81b91324ceffe1fa22318de1ffad96/pkg/signature/rsapss.go#L147 work for this?

**Comment by haydentherapper** [comment]
Yea, we would need to call those from the functions I linked. The primary change would need to be distinguishing between pkcs1 and pss for rsa. But fwiw, there is a comment to that effect already, so maybe we should just mark as WAI
