### ISSUE TITLE
Workload Identity Federation is not working with GCP KMS support

### ISSUE THREAD

**Issue by developer-guy** [sigstore/sigstore#138]
**Description**

 Recently, we (w/@dentrax @erkanzileli) added other key management system support to Kyverno while verifying image signatures.[^1] Then, I tried this feature on GCP while using GCP KMS and GKE. To achieve this I took advantage of Workload Identity Federation[^2]. To enable this I've used the following commands:

🎗 Cross-ref: https://github.com/kyverno/website/pull/376

```shell
$ export PROJECT_ID=$(gcloud config get-value project)
$ export CLUSTER_NAME="gke-wif"
$ gcloud container clusters create $CLUSTER_NAME \
    --workload-pool=$PROJECT_ID.svc.id.goog --num-nodes=2
$ export GSA_NAME=kyverno-sa
$ gcloud iam service-accounts create $GSA_NAME
$ gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:${PROJECT_ID}.svc.id.goog[kyverno/kyverno]" \
  ${GSA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
$ gcloud projects add-iam-policy-binding ${PROJECT_ID} \
  --role roles/cloudkms.admin \
  --member serviceAccount:${GSA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
$ kubectl annotate serviceaccount \
  --namespace kyverno \
  kyverno \
  iam.gke.io/gcp-service-account=${GSA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
```

Then, I tried it with Kyverno but it didn't work as I expected. So, I decided to do a small test together with the `google/cloud-sdk:slim` image. So, I ran a Pod with this image, everything worked fine.

```shell
kubectl run -it --rm \
  --image google/cloud-sdk:slim \
  --serviceaccount kyverno \
  --namespace kyverno \
  workload-identity-test
```

![Screen Shot 2021-11-11 at 15 53 53](https://user-images.githubusercontent.com/16693043/141303512-7da6ed46-eec6-46c8-a9fd-53997132886a.png)

[^1]: https://github.com/kyverno/kyverno/pull/2607
[^2]: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

cc: @JimBugwadia @dlorenc @cpanato

**Comment by endorama** [comment]
I took a look, my initial hypothesis was that the GCP SDK library in use by `cosign` is not up to date and lacks that functionality. 

I say `cosign` as is the packages used in the linked PR.

The `google/cloud-sdk:slim` image used SDK version 364.0.0 ([extracted from `Dockerfile`](https://hub.docker.com/layers/google/cloud-sdk/slim/images/sha256-dfa69efeb9f002e7cce49d47000245d22f811001e672d37b45d633fe19aa31da?context=explore))

`cosign` [is using](https://github.com/sigstore/cosign/blob/5468ddce1f5fc024762f5875de5cafec42adede8/go.mod#L36) `google.golang.org/api` package at version `v0.60.0`, which as of today is the latest version.

So I would not expect this to be a version related issue.

Following GKE documentation about [using Workload Identity from code](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#using_from_your_code) I suspect there are issues in the authentication code; it may be is not performing authentication is a way that supports metadata authentication, as per GCP docs:

>  Existing code that authenticates using the instance metadata server (like code using the Google Cloud client libraries) should work without modification.

**Comment by endorama** [comment]
Upon further investigation, `cosign` has a Google provider called `google-workload-identity` ([link](https://github.com/sigstore/cosign/blob/main/pkg/providers/google/google.go#L30))

So my new hypothesis is that Kyverno is not selecting this provider when using cosign. @developer-guy may you test this? (I don't have a setup to test it)

**Comment by JimBugwadia** [comment]
Hi @endorama - thanks for the details! Can you please elaborate on `Kyverno is not selecting this provider when using cosign` - is there an example of how to select the provider that we can reference? 

Currently, Kyverno is (indirectly - via Cosign [signatures.LoadPublicKey](https://github.com/sigstore/cosign/blob/7066f122b8288e5621cf7e3dca600075bb70cd47/pkg/signature/keys.go#L40)) calling [kms.Get](https://github.com/sigstore/sigstore/blob/v1.0.0/pkg/signature/kms/kms.go#L68) to load the providers.

Also, worth noting that the Kyverno build is currently using `disable_gcp` tag based on prior guidance - could that have any impact? I don't see any use of this tag in the Sigstore repos. See: https://github.com/kyverno/kyverno/blob/main/Makefile#L28.

**Comment by developer-guy** [comment]
Hello @lukehinds, as I mentioned above, recently, we've added other key supports for verification by using cosign to Kyverno. As you already know, KMS is one of them, so, I wanted to test this by deploying Kyverno on GKE and using GCP KMS for storing keys. But, to access my keys on GCP KMS, Kyverno should use Workload Identity, I did everything to make it work, but it didn't work. So, I thought that the reason for this is that Kyverno is using sigstore internally for authentication to use GCP services.

**Comment by endorama** [comment]
> Also, worth noting that the Kyverno build is currently using disable_gcp tag based on prior guidance - could that have any impact? I don't see any use of this tag in the Sigstore repos. See: kyverno/kyverno@main/Makefile#L28.

I've not been able to find `disable_gcp` string in neither [`cosign`](https://github.com/sigstore/cosign/search?q=disable_gcp) nor [`sigstore`](https://github.com/sigstore/sigstore/search?q=disable_gcp&type=code) so I'm not sure what that tag is expected to do. 

> Can you please elaborate on Kyverno is not selecting this provider when using cosign - is there an example of how to select the provider that we can reference?
> Currently, Kyverno is (indirectly - via Cosign signatures.LoadPublicKey) calling kms.Get to load the providers.

I looked into the `cosign` sources, while you are pointing to `sigstore` so I'm not sure what I said make sense. Indeed is most probably wrong.
I'll dig into the `sigstore` GCP code later.

**Comment by developer-guy** [comment]
I found this but am not sure whether it refers to our problem but this [--k8s-keychain flag](https://github.com/sigstore/cosign/blob/90e2dcfe7b92223221a44b2fc16ade64de09f2c9/cmd/cosign/cli/options/registry.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46-L47) seems to help us because I found these two blog posts and all of them use this flag to enable workload identity feature, am I right @mattmore @dlorenc?

* https://gortega.medium.com/protecting-the-supply-chain-signing-container-images-without-needing-to-manage-signing-keys-686f9b45b2d3
* https://chainguard.dev/posts/2021-11-03-zero-friction-keyless-signing

**Comment by JimBugwadia** [comment]
@endorama regarding:
> I've not been able to find disable_gcp string in neither cosign nor sigstore so I'm not sure what that tag is expected to do.

As an example, the tag is used here: https://github.com/google/go-containerregistry/blob/main/pkg/authn/k8schain/k8schain_gcp.go#L2. 

I am not sure if this has any implications on using workload identities to allow a pod to use the cloud provider KMS.

**Comment by dlorenc** [comment]
I don't see any reason this shouldn't work. @developer-guy could you explain a bit more what error you hit when trying to use KMS with workload identity federation from here:

> Then, I tried it with Kyverno but it didn't work as I expected

Was there an error?

**Comment by developer-guy** [comment]
seems everything fine but I couldn't make it work 🤦🏻‍♂️

**Comment by JimBugwadia** [comment]
Hi @developer-guy - was your latest test with Kyverno 1.6 RC? 

Here are some recent / related changes and discussions in this area:

https://github.com/kyverno/kyverno/issues/3019
https://github.com/kyverno/kyverno/pull/3036

If needed, lets setup some time to troubleshoot and get this figured out.

**Comment by ribbybibby** [comment]
In 1.6, the cloud provider keychains are only setup when the 'kubernetes keychain' is initialized and that only happens if there are image pull secrets specified by the flag `-imagePullSecrets`.

I think this PR needs to land in a Kyverno release before workload identity will work off the bat: https://github.com/kyverno/kyverno/pull/3116.

@developer-guy a workaround you can use in the meantime is to create an empty image pull secret and use that:
```
apiVersion: v1
kind: Secret
metadata:
  name: annoying-unnecessary-secret
data:
  # content is {}
  .dockerconfigjson: e30K
type: kubernetes.io/dockerconfigjson
```

**Comment by ribbybibby** [comment]
This was cherry picked into 1.6 here: https://github.com/kyverno/kyverno/pull/3166.

Seems to be working for me in v1.6.0-rc3. Could you confirm if this has solved your issues @developer-guy?

**Comment by developer-guy** [comment]
I'm asking for making it clear, do you want me to try the demo on more time with kyverno 1.6.0-rc3 ? Do I need to do anything than that ? Thank you

**Comment by ribbybibby** [comment]
@developer-guy Yes, please :bow: 

If it still doesn't work, then it would nice to have some more details:
- Any error messages from Kyverno's logs
- More information about the image you're trying to verify. For instance, is it in a private registry, is that Google Container Registry, Artifact Registry or a non-GCP registry?

**Comment by developer-guy** [comment]
Hello @ribbybibby, here is the result of verifying my container image stored in public GCP registry against a key stored in GCP KMS:

<details>

<summary> Cosign Verify result </summary>

```shell
 cosign verify -key gcpkms://projects/$(gcloud config get-value project)/locations/global/keyRings/test/cryptoKeys/cosign/versions/1 gcr.io/$(gcloud config get-value project)/alpine:3.15.0
zsh: correct 'config' to '.config' [nyae]? n
zsh: correct 'config' to '.config' [nyae]? n
WARNING: the flag -key is deprecated and will be removed in a future release. Please use the flag --key.

Verification for gcr.io/neon-metric-340311/alpine:3.15.0 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"gcr.io/neon-metric-340311/alpine"},"image":{"docker-manifest-digest":"sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300"},"type":"cosign container image signature"},"optional":null}]
```
</details>


Here is the output of the kyverno pod and the version information:

<details>

<summary> Kyverno Log and version information </summary>

```shell
$ helm upgrade --install kyverno --namespace kyverno kyverno/kyverno --create-namespace  --set resources.limits.memory=512Mi --set image.tag=v1.6.0-rc3 --set initImage.tag=v1.6.0-rc3 --set extraArgs="{--autoUpdateWebhooks=false,--backgroundScan=30s}" --set replicaCount=3

$ kubectl images -n kyverno
[Summary]: 1 namespaces, 3 pods, 6 containers and 2 different images
+--------------------------+--------------------+---------------------------------------+
|         PodName          |   ContainerName    |            ContainerImage             |
+--------------------------+--------------------+---------------------------------------+
| kyverno-589c98d8f7-jmklx | kyverno            | ghcr.io/kyverno/kyverno:v1.6.0-rc3    |
+                          +--------------------+---------------------------------------+
|                          | (init) kyverno-pre | ghcr.io/kyverno/kyvernopre:v1.6.0-rc3 |
+--------------------------+--------------------+---------------------------------------+
| kyverno-589c98d8f7-tg8zz | kyverno            | ghcr.io/kyverno/kyverno:v1.6.0-rc3    |
+                          +--------------------+---------------------------------------+
|                          | (init) kyverno-pre | ghcr.io/kyverno/kyvernopre:v1.6.0-rc3 |
+--------------------------+--------------------+---------------------------------------+
| kyverno-589c98d8f7-tsm5x | kyverno            | ghcr.io/kyverno/kyverno:v1.6.0-rc3    |
+                          +--------------------+---------------------------------------+
|                          | (init) kyverno-pre | ghcr.io/kyverno/kyvernopre:v1.6.0-rc3 |
+--------------------------+--------------------+---------------------------------------+


 1 server.go:333] WebhookServer/MutateWebhook "msg"="image verification failed" "error"="\n\nresource Pod/default/signed was blocked due to the following policies\n\ncheck-image:\n  check-image: 'image verification failed for gcr.io/neon-metric-340311/alpine:3.15.0:\n    loading credentials: open gcpkms:/projects/neon-metric-340311/locations/global/keyRings/test/cryptoKeys/cosign/versions/1:\n    no such file or directory'\n" "gvk"="/v1, Kind=Pod" "kind"="Pod" "name"="signed" "namespace"="default" "operation"="CREATE" "uid"="07f9176c-39ee-4679-b7b4-507d57e173a7"
kyverno-589c98d8f7-tg8zz kyverno I0204 12:36:17.269953       1 imageVerify.go:172] EngineVerifyImages "msg"="verifying image" "kind"="Pod" "name"="signed" "namespace"="default" "policy"="check-image" "image"="gcr.io/neon-metric-340311/alpine:3.15.0"
kyverno-589c98d8f7-tg8zz kyverno I0204 12:36:17.559690       1 imageVerify.go:206] EngineVerifyImages "msg"="failed to verify image" "kind"="Pod" "name"="signed" "namespace"="default" "policy"="check-image" "duration"=0.289564003 "error"="loading credentials: open gcpkms:/projects/neon-metric-340311/locations/global/keyRings/test/cryptoKeys/cosign/versions/1: no such file or directory" "image"="gcr.io/neon-metric-340311/alpine:3.15.0"
kyverno-589c98d8f7-tg8zz kyverno I0204 12:36:17.560158       1 common.go:60] WebhookServer "msg"="spec.ValidationFailureAction set to enforce blocking resource request" "action"="verifyImages" "gvk"="/v1, Kind=Pod" "operation"="CREATE" "resource"="default/Pod/signed" "policy"="check-image"
kyverno-589c98d8f7-tg8zz kyverno E0204 12:36:17.560821       1 server.go:333] WebhookServer/MutateWebhook "msg"="image verification failed" "error"="\n\nresource Pod/default/signed was blocked due to the following policies\n\ncheck-image:\n  check-image: 'image verification failed for gcr.io/neon-metric-340311/alpine:3.15.0:\n    loading credentials: open gcpkms:/projects/neon-metric-340311/locations/global/keyRings/test/cryptoKeys/cosign/versions/1:\n    no such file or directory'\n" "gvk"="/v1, Kind=Pod" "kind"="Pod" "name"="signed" "namespace"="default" "operation"="CREATE" "uid"="b0537638-6d49-4118-91

```
</details>

Here is the Clusterpolicy:

```YAML
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "gcr.io/neon-metric-340311/alpine:*"
        key: "gcpkms://projects/neon-metric-340311/locations/global/keyRings/test/cryptoKeys/cosign/versions/1"
```

Same error happens:

```shell
$ kubectl run signed --image=gcr.io/$(gcloud config get-value project)/alpine:3.15.0                                                                                           
Error from server: admission webhook "mutate.kyverno.svc-ignore" denied the request:

resource Pod/default/signed was blocked due to the following policies

check-image:
  check-image: 'image verification failed for gcr.io/neon-metric-340311/alpine:3.15.0:
    loading credentials: open gcpkms:/projects/neon-metric-340311/locations/global/keyRings/test/cryptoKeys/cosign/versions/1:
    no such file or directory'
```

cc: @ribbybibby

**Comment by ribbybibby** [comment]
Okay, if it's a public image then the keychain is probably nothing to do with it.

KMS definitely works for me with workload identity, so I suspect it might be a configuration issue in your environment.

What service account are the kyverno pods using? I notice from your original post that you were attaching workload identity to a service account called 'kyverno-service-account' but I think helm usually creates and uses a service account called just 'kyverno'.

**Comment by developer-guy** [comment]
Yep, I noticed that to so, I've updated it as "kyverno", it didn't work also 🥲

**Comment by ribbybibby** [comment]
Was the `cosign verify` command you posted above executed in a pod in the same cluster with the same service account as kyverno?

**Comment by developer-guy** [comment]
kindly ping @ribbybibby 🙋🏻‍♂️ would you mind sharing your commands with me? Then I'll be able to execute them to test Kyveno v1.6.0 with workload identity feature to verify container images, WDYT? Because mine was not worked and don't know why 🤷🏻‍♂️

**Comment by developer-guy** [comment]
Because I want to write a blog post about it also, see.
https://github.com/kyverno/website/pull/376

**Comment by developer-guy** [comment]
kindly ping @ribbybibby 🙋🏻‍♂️

**Comment by ribbybibby** [comment]
There's quite a few moving parts in the setup, but here's more or less the terraform I'm using for the KMS key and the service account:
```
resource "google_kms_key_ring" "my_project" {
  name     = "my-keyring"
  project  = "my-project"
  location = "europe-west1"
}

resource "google_kms_crypto_key" "cosign" {
  name     = "cosign"
  key_ring = google_kms_key_ring.my_project.self_link
  purpose  = "ASYMMETRIC_SIGN"

  lifecycle {
    prevent_destroy = true
  }

  version_template {
    algorithm = "EC_SIGN_P256_SHA256"
  }
}

resource "google_service_account" "kyverno" {
  project    = "my-project"
  account_id = "kyverno"
}

resource "google_service_account_iam_binding" "kyverno" {
  service_account_id = google_service_account.kyverno.name
  role               = "roles/iam.workloadIdentityUser"

  members = [
    "serviceAccount:my-project.svc.id.goog[kyverno/kyverno]"
  ]
}

resource "google_kms_crypto_key_iam_binding" "kyverno-verifier" {
  crypto_key_id = "projects/my-project/locations/europe-west1/keyRings/my-keyring/cryptoKeys/cosign"
  role          = "roles/cloudkms.verifier"

  members = [
    "serviceAccount:${google_service_account.kyverno.email}",
  ]
}

resource "google_kms_crypto_key_iam_binding" "kyverno-viewer" {
  crypto_key_id = "projects/my-project/locations/europe-west1/keyRings/my-keyring/cryptoKeys/cosign"
  role          = "roles/cloudkms.viewer"

  members = [
    "serviceAccount:${google_service_account.kyverno.email}",
  ]
}

resource "google_project_iam_member" "kyverno-gcr" {
  project = "my-project"
  role    = "roles/storage.objectViewer"
  member  = "serviceAccount:${google_service_account.kyverno.email}"
}
```

Comparing this to your original scripts, I can see that you're using the `roles/cloudkms.admin` whereas I'm using `roles/cloudkms.viewer` and `roles/cloudkms.verifier`. From https://cloud.google.com/kms/docs/reference/permissions-and-roles:

**Comment by haydentherapper** [comment]
I believe this is now fixed, please reopen if not
