### ISSUE TITLE
Fix golangci-lint

### ISSUE THREAD

**Issue by dlorenc** [sigstore/sigstore#154]
I think we need to bump something in the config. Lint errors have started popping up that weren't before. You can see this here: https://github.com/sigstore/sigstore/runs/4303559748?check_suite_focus=true

**Comment by hectorj2f** [comment]
Perhaps we could stick to `uses: golangci/golangci-lint-action@v2.5.2` to be consistent with the other repos.

**Comment by naveensrinivasan** [comment]
It was because of this PR https://github.com/sigstore/sigstore/pull/148
