### ISSUE TITLE
feat: auto-close browser window after auth success

### ISSUE THREAD

**Issue by stgarf** [sigstore/sigstore#1617]
**Auto-close the browser window after successful authentication**

To enhance QoL and user experience when using sigstore/cosign/gitsign often, this feature should automatically close the authentication window once the user successfully logs in, thereby streamlining the signing process and reducing unnecessary interactions after authenticating. Prior to this, users manually close the window, a step that can be easily become tedious, leading to a cluttered browser (I know, what a problem to have!).

**Comment by stgarf** [comment]
I have a WIP that I've been testing locally with `gitsign` and it's been pretty good so far.
https://github.com/sigstore/sigstore/compare/main...stgarf:sigstore:feature/autoclose-auth-page

**Comment by priyawadhwa** [comment]
That sounds great! If you wanna go ahead and open a PR I can review it :)

**Comment by bobcallaway** [comment]
@wlynch @imjasonh didn't one of you attempt this before and run into a road block?
