### ISSUE TITLE
CVE in go-tuf please upgrade to go-tuf/v2

### ISSUE THREAD

**Issue by xnox** [sigstore/sigstore#1857]
**Description**

https://github.com/theupdateframework/go-tuf/security/advisories/GHSA-4f8r-qqr9-fq8j

Is a security vulnerability that affects go-tuf, which is fixed in v2 API series, please upgrade to the /v2 module

Note the rewrite of the go-tuf api at https://github.com/theupdateframework/go-tuf?tab=readme-ov-file#history---legacy-go-tuf-vs-go-tufv2

**Version**

all.

**Comment by haydentherapper** [comment]
go-tuf v0.7.0 is not affected by the vulnerability. I've discussed this with the go-tuf maintainers and they'll be updated the GHSA.

We will not be updating this Sigstore TUF client to go-tuf v2 as we have already rewritten the client. Use https://pkg.go.dev/github.com/sigstore/sigstore-go/pkg/tuf instead, which is based on go-tuf v2.
