### ISSUE TITLE
FuzzUnmarshalCertificatesFromPEM exceeds 60 seconds for the test case

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/sigstore#188]
**Description**
oss-fuzz failure issue
[clusterfuzz-testcase-minimized-FuzzUnmarshalCertificatesFromPEM-4710187355734016.zip](https://github.com/sigstore/sigstore/files/7676542/clusterfuzz-testcase-minimized-FuzzUnmarshalCertificatesFromPEM-4710187355734016.zip)
```
Project: sigstore
Fuzzing Engine: libFuzzer
Fuzz Target: FuzzUnmarshalCertificatesFromPEM
Job Type: libfuzzer_asan_sigstore
Platform Id: linux

Crash Type: Timeout (exceeds 60 secs)
Crash Address: 
Crash State:
  FuzzUnmarshalCertificatesFromPEM
  

```

**Comment by naveensrinivasan** [comment]
This is an issue with `removeSpacesAndTab` from go standard library
![profile001](https://user-images.githubusercontent.com/172697/145691611-efa338c4-6914-4a99-a6e8-f1b86bade9e4.png)

**Comment by naveensrinivasan** [comment]
Opened an issue https://github.com/golang/go/issues/50116. This is an issue with go standard library.

**Comment by haydentherapper** [comment]
Closing as inactionable
