### ISSUE TITLE
Fuzz - Timeout in FuzzUnmarshalPEMToPublicKey

### ISSUE THREAD

**Issue by naveensrinivasan** [sigstore/sigstore#198]
**Description**

The  FuzzUnmarshalPEMToPublicKey exceeds the time limit in `oss-fuzz` 
[clusterfuzz-testcase-minimized-FuzzUnmarshalPEMToPublicKey-6640464978116608.log](https://github.com/sigstore/sigstore/files/7699139/clusterfuzz-testcase-minimized-FuzzUnmarshalPEMToPublicKey-6640464978116608.log)

**Comment by naveensrinivasan** [comment]
The root cause of this issue is in Go Standard library https://github.com/golang/go/issues/50116

**Comment by haydentherapper** [comment]
Closing as outdated
