### ISSUE TITLE
Adding more authentication options to Azure KMS

### ISSUE THREAD

**Issue by simongottschlag** [sigstore/sigstore#223]
**Description**

Hi!

Great job you have been doing here! 😊

When looking at cosign I noticed that the Azure KMS integration only supports a service principal through the environment - but there are lots of other methods available from the Azure SDK.

Is there a specific reason to only support one of them or would you be open to a PR that adds support for MSI (Managed Service Identity) and Azure CLI (if you are authenticated using the cli, use the credentials from there).

I would be willing to try and add some additional support if you want! 👍

**Comment by cpanato** [comment]
@simongottschlag thanks! yes, that sounds very interesting, you can work to add the other options to authenticate, I will be happy to review and test it

**Comment by simongottschlag** [comment]
@cpanato I've created a PR. :+1:
