### ISSUE TITLE
Plan verify operation

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore#28]
[WIP] still fleshing this out, but wanted to open this up for others to provide input.

Key focus should be the end UX. This needs to be as simple as we can possibly make it for end users. They should be able to just say 'verify' to consider something 'trusted' with zero setup and as few as possible manual steps. Having said that, those who want to dig deeper should be able to, but a majority of users won't want to and they will consider it an annoyance to have to perform any checks themselves (we know this from the amount of users who currently don't even bother to verify with existing tools. Users will even mash away at `Y/n` prompts with very little attention or patience). This should be as seamless as possible.

I am imagining a system where projects can set their own policy and maintain it for their users.  We provide project owners / maintainers the ability to bootstrap and control their own policy.

The CLI will allow a project owner to seed a new project with the first signed project policy entry that can be stored in rekor and the project repository. 

`sigstore --init github.com/johndoe/widget_proj`

```json
{
  "project": "github.com/janedoe/widget_proj",
  "owner": "janedoe@gmail.com",
  "policy_version": 2.1,
  "active_since": "2012-08-06T00:00:00.000Z",
  "sign_algorithm": "ecdsa-p384",
  "sign_threshold": 2,
  "maintainers": [
    {
      "name": "Jessica Doe",
      "email": [
        "jessica@example.com",
        "jessica@example.org"
      ],
      "active_since": "2014-06-25T00:00:00.000Z"
      "allow_device_flow_auth:" true
    },
    {
      "name": "Justin Doe",
      "email": [
        "justin@example.com"
      ],
      "active_since": "2017-02-09T00:00:00.000Z"
      "allow_device_flow_auth:" false
    }
     {
      "name": "James Doe",
      "email": [
        "james@example.com"
      ],
      "active_since": "2020-10-09T00:00:00.000Z"
      "allow_device_flow_auth:" false
    }
  ]
}
```

Some more details

`project:` the namespace of the project (this could be a pypi link, crates.io url etc)
`owner:` the individual that controls the project and performs the genesis signing of the projects policy and later policy updates.
`policy_version:` versioning number for the policy
`sign_algorithm:` explains itself (projects should be able to pivot as they need (algorithm agility)
`sign_threshold:` the amount of `maintainers` needed to sign an artifact for it be considered 'trusted'. Users could possible override this for releases they consider pre-release etc (or higher for prod bound releases)
* `maintainers:` users who can sign an artifact
   * `email:` the `maintainers` OIDC account
   * `active_since:` can prevent a user being a threshold element for signing past releases
   * `allow_device_flow_auth:` can the account be used as a device flow / unattended signee.

Some other fields we could include. There can be a `genesis_key` where the project owner bootstraps the trust with an offline key stored in a yubikey / HSM.

**Comment by endorama** [comment]
> project: the namespace of the project (this could be a pypi link, crates.io url etc)

Is `project` expected to link to the source or to the packages? I see two possible situations, one where you have the project only once (by linking to the source) and one where you have it multiple times (source + packaged version).
From my understanding that would impact the `--init` phase (one vs multiple `init`)

**Comment by lukehinds** [comment]
> > project: the namespace of the project (this could be a pypi link, crates.io url etc)
> 
> Is `project` expected to link to the source or to the packages? I see two possible situations, one where you have the project only once (by linking to the source) and one where you have it multiple times (source + packaged version).
> From my understanding that would impact the `--init` phase (one vs multiple `init`)

Its more of a namespace at the moment that packagers could reference, no interaction with the source.

**Comment by endorama** [comment]
@lukehinds thanks.

As a user, I would love to be able to just run `sigstore verify <artefact>` and have the tool show all the performed operations (along the line of what `cosign` does with "The following checks were performed").

I have a couple of questions:
1. as a user, why should I trust this automated verification? I'm playing devils advocate here, but the reasoning is trying to dig a bit deeper in how much information is needed to consider the automation trustworthy from the POV of an end user without any other knowledge of the tooling. In my opinion this affects the UX a lot, I think that verbose or difficult to comprehend output plays a major role in distancing users from security tools.
2. as the tool, how do I know which policy should I use to validate an artefact?

(I love the idea of a public policy that a tool can use to perform the verification without any user interaction.)

**Comment by lukehinds** [comment]
was just speaking with @dlorenc and there is some overlap with this issue: https://github.com/sigstore/cosign/issues/86

**Comment by mnm678** [comment]
As discussed in the meeting, the TUF targets metadata format is described [here](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#file-formats-targetsjson-and-delegated-target-roles--file-formats-targets). It actually includes a lot of the same fields as this proposal, with the addition of delegations. There's also some information later in that link about how the TUF verification works.

This is the metadata that will (very soon) be [supported by PyPI](https://www.python.org/dev/peps/pep-0458/#pypi-and-tuf-metadata), so using it would let the tooling interoperate.

**Comment by elinesterov** [comment]
How to verify the trust of the policy? Should it be signed by the owner (and follow threshold specification)? Do we plan to do it through the fulcio and have a record in recor? 
Where the policy should be stored? As one of the artifacts as a part of the release like source code?

**Comment by lukehinds** [comment]
> How to verify the trust of the policy? 

project owner signs it, this fixes it to an OpenID scope, using a long term keypair could be possible as well

> Should it be signed by the owner (and follow threshold specification)? 

Yes, owner would sign. A threshold could be a possibly for the policy as well, we could factor that into the schema.

> Do we plan to do it through the fulcio and have a record in recor?

Yes

> Where the policy should be stored? As one of the artifacts as a part of the release like source code?

In rekor / ctl and then specific to the packaging system (this I need to plan out and I am open to suggestions).
