### ISSUE TITLE
Using sigstore in CNCF projects

### ISSUE THREAD

**Issue by dims** [sigstore/sigstore#384]
Folks,

There are a bunch of MPL libraries here:
https://github.com/sigstore/sigstore/blob/main/go.mod#L58-L75

CNCF only allows a handful of MPL'ed libraries from hashicorp:
https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2019-11-01.json#L23-L46

the CNCF policy is written down here:
https://github.com/cncf/foundation/tree/main/license-exceptions

Question is ... what do we do next?

**Comment by bobcallaway** [comment]
@cpanato FYI

**Comment by dims** [comment]
sounds good @dlorenc

**Comment by dlorenc** [comment]
We should confirm go.mod actually works that way though since I might just be making that up...

**Comment by mattmoor** [comment]
FYI the tooling in `google/licenseclassifier` and `google/go-licenses` can be used to flag forbidden licenses presubmit.

You'd have to customize the forbidden license list it uses to include MPL, but I believe it'll do the trick, if that's interesting to folks.

**Comment by cpanato** [comment]
using `go mod why`
here is a list

- `github.com/hashicorp/errwrap`
```
$ go mod why github.com/hashicorp/errwrap
# github.com/hashicorp/errwrap
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/errwrap
```

- `github.com/hashicorp/go-cleanhttp`
```
$ go mod why github.com/hashicorp/go-cleanhttp
# github.com/hashicorp/go-cleanhttp
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-cleanhttp
```

- `github.com/hashicorp/go-hclog`
```
$ go mod why github.com/hashicorp/go-hclog
# github.com/hashicorp/go-hclog
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/go-hclog
```

- `github.com/hashicorp/go-immutable-radix`
```
$ go mod why github.com/hashicorp/go-immutable-radix
# github.com/hashicorp/go-immutable-radix
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/physical
github.com/armon/go-metrics
github.com/hashicorp/go-immutable-radix
```

- `github.com/hashicorp/go-multierror`
```
$ go mod why github.com/hashicorp/go-multierror
# github.com/hashicorp/go-multierror
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-multierror
```

- `github.com/hashicorp/go-plugin`
```
$ go mod why github.com/hashicorp/go-plugin
# github.com/hashicorp/go-plugin
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/helper/pluginutil
github.com/hashicorp/go-plugin
```

- `github.com/hashicorp/go-retryablehttp`
```
$ go mod why github.com/hashicorp/go-retryablehttp
# github.com/hashicorp/go-retryablehttp
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-retryablehttp
```

- `github.com/hashicorp/go-rootcerts`
```
$ go mod why github.com/hashicorp/go-rootcerts
# github.com/hashicorp/go-rootcerts
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-rootcerts
```

- `github.com/hashicorp/go-secure-stdlib/mlock`
```
$ go mod why github.com/hashicorp/go-secure-stdlib/mlock
# github.com/hashicorp/go-secure-stdlib/mlock
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/helper/pluginutil
github.com/hashicorp/go-secure-stdlib/mlock
```

- `github.com/hashicorp/go-secure-stdlib/parseutil`
```
$ go mod why github.com/hashicorp/go-secure-stdlib/parseutil
# github.com/hashicorp/go-secure-stdlib/parseutil
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-secure-stdlib/parseutil
```

- `github.com/hashicorp/go-secure-stdlib/strutil`
```
$ go mod why github.com/hashicorp/go-secure-stdlib/strutil
# github.com/hashicorp/go-secure-stdlib/strutil
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-secure-stdlib/parseutil
github.com/hashicorp/go-secure-stdlib/strutil
```

- `github.com/hashicorp/go-sockaddr`
```
$ go mod why github.com/hashicorp/go-sockaddr
# github.com/hashicorp/go-sockaddr
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/go-secure-stdlib/parseutil
github.com/hashicorp/go-sockaddr
```

- `github.com/hashicorp/go-uuid`
```
$ go mod why github.com/hashicorp/go-uuid
# github.com/hashicorp/go-uuid
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/helper/pluginutil
github.com/hashicorp/go-uuid
```

- `github.com/hashicorp/go-version`
```
$ go mod why github.com/hashicorp/go-version
# github.com/hashicorp/go-version
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/helper/pluginutil
github.com/hashicorp/go-version
```

- `github.com/hashicorp/golang-lru`
```
$ go mod why github.com/hashicorp/golang-lru
# github.com/hashicorp/golang-lru
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/physical
github.com/hashicorp/golang-lru
```

- `github.com/hashicorp/hcl`
```
$ go mod why github.com/hashicorp/hcl
# github.com/hashicorp/hcl
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/hcl
```

- `github.com/hashicorp/vault/sdk`
```
$ go mod why github.com/hashicorp/vault/sdk
# github.com/hashicorp/vault/sdk
(main module does not need package github.com/hashicorp/vault/sdk)
```

- `github.com/hashicorp/yamux`
```
$ go mod why github.com/hashicorp/yamux
# github.com/hashicorp/yamux
github.com/sigstore/sigstore/pkg/signature/kms/hashivault
github.com/hashicorp/vault/api
github.com/hashicorp/vault/sdk/logical
github.com/hashicorp/vault/sdk/helper/pluginutil
github.com/hashicorp/go-plugin
github.com/hashicorp/yamux
```

**Comment by dims** [comment]
@eddiezane indirect we can live with. here it did not seem indirect. (you can test by running `go mod vendor` and inspect what gets dropped in the directories rather then guessing from go.sum)

**Comment by mattmoor** [comment]
From @cpanato's dump it looks like most of this is pulled in through the Vault KMS integration.  The various KMS integrations suck in a ton of dependencies, and this has been something I've had my eye on for some time to refactor, especially since it lives in such a core library.

I've had a picture forming in my head for a little while now, let me open an issue to track this and dump my thoughts in there to avoid hijacking this.

**Comment by mattmoor** [comment]
It looks like @imjasonh read my mind and already did a great job refactoring some of the KMS libraries, but the places we link them are still far to central to `cosign` itself.  I've moved the imports into the binary entrypoints here: https://github.com/sigstore/cosign/pull/1744 which should hopefully enable downstream things that vendor cosign to be able to pick and choose which of these they want/need.

**Comment by dims** [comment]
@mattmoor when will this set of changes be in a tagged release? (or has that happened already?)

**Comment by mattmoor** [comment]
Should be in 1.8

lmk if there is anything lingering

**Comment by dims** [comment]
thanks @mattmoor
