### ISSUE TITLE
verification of `gcpkms://` requires overly broad permissions

### ISSUE THREAD

**Issue by mattmoor** [sigstore/sigstore#467]
**Description**

I was looking at the permissions needed by the `ClusterImagePolicy -> ConfigMap` reconciler to deal with KMS, and it seems to require `cloudkms.cryptoKeys.get`, where I'd expect it to only need `cloudkms.cryptoKeyVersions.viewPublicKey`.

I can understand the *signing* path requiring more capabilities, but for things like the admission controller and `cosign verify` flows, it should be doable by folks that only have public key access.

cc @dekkagaijin @imjasonh

**Comment by imjasonh** [comment]
Looks like we do a bunch of validation that the key exists, and cache it with a TTL, and that's why we `Get` it instead of just using it.

https://github.com/sigstore/sigstore/blob/845467ef3d8df5ab991f5ecf3a5f4aac747a9f14/pkg/signature/kms/gcp/client.go#L177

**Comment by haydentherapper** [comment]
Closing as WAI
