### ISSUE TITLE
Enforcement of a digest looking like a digest

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore#479]
**Description**

There's an interesting forgery for ECDSA where it's possible to forge a valid signature over a random value for a fixed public key. To defend against this, it's necessary to first hash a message before signing or verifying it. For ED25519, this is handled via a pre-hash, while for ECDSA, it's standard practice to first hash the message.

However, for the hashedrekord type, it's a requirement that we verify against a digest without hashing again. This is why we support `WithDigest`. This makes `WithDigest` unsafe. We can help defend against this if there is a check beforehand that the digest look like a digest, so a random value isn't accepted. For example, Rekor [checks](https://github.com/sigstore/rekor/blob/main/pkg/types/hashedrekord/v0.0.1/entry.go#L171-L173) that the digest matches a SHA256 regex.

This is not a full proof approach, as it is still possible that a random value look like a digest, it's just hard to find such a value for this forgery (I think this is true, but I'd need someone more well-versed in elliptic curve crypto to verify this).

We should add a) warnings in comments about the dangers of verifying with a digest, and b) move the rekor checks into here to enforce that a digest looks like a digest.

**Comment by znewman01** [comment]
To clarify, you're referring to [this](https://www.metzdowd.com/pipermail/cryptography/2017-March/031755.html)?

> For example, Rekor [checks](https://github.com/sigstore/rekor/blob/main/pkg/types/hashedrekord/v0.0.1/entry.go#L171-L173) that the digest matches a SHA256 regex.

[That validator](https://github.com/asaskevich/govalidator/blob/f21760c49a8d602d863493de796926d2a5c1138d/validator.go#L709) just checks that the string is a hex-encoding of the proper length, so it doesn't defend against this attack at all.

That said, I don't think this is actually a problem. The full ECDSA signature algorithm *includes* the hashing step, so it's not true that this lets you forge *signatures* over random *messages*. You can just forge something that looks like a signature over something that looks like the hash of a message.

When we ingest HashedRekord data to Rekor, we don't "validate the signature" so much as "check that the signature is well-formed." To my mind, this is totally okay. I would prefer people not put garbage in Sigstore, but no clients should assume that a signature is valid without checking it themselves. And, in doing that, they would be checking it against the actual message in two steps: check the signature over the hash, *and* check that the hash matches the data.

Can you think of any circumstance in which a client sees a HashedRekord and wants to check the signature, but not by checking it *against* some data?

**Comment by haydentherapper** [comment]
To add some context, I've been looking at entry malleability in Rekor. This isn't security critical for Rekor - Being able to forge an entry is detectable like you said, since you will be checking for the presence of an entry. Similarly, being able to modify a signature does not present a real risk (ECDSA signatures are malleable) because the artifact still must have been signed first.

The "threat" is that an "attacker" (using quotes liberally cause it's not a real risk) can create a forged entry for a given identity, and this could set off a monitor. I'm starting to look at closing those gaps. Rekor defends against this already with a regex, but I'd like to push the regex into sigstore/sigstore in case someone else uses these libraries for something other than transparency logs - Then this can become a security risk depending on use.

**Comment by haydentherapper** [comment]
IIUC, the regex is an acceptable defense because it's unlikely that you can form random garbage to match that regex. It's still technically possible, however very unlikely, but given that it's not a security risk, I don't see a need to defend against it with more than just a regex.

**Comment by znewman01** [comment]
> The "threat" is that an "attacker" (using quotes liberally cause it's not a real risk) can create a forged entry for a given identity, and this could set off a monitor.

Ahh yeah, great point. This is possible. It's more "spam" than anything else, but it's "spam that might cause a page to some poor security engineer who has to panic figuring out whether this is a real issue."

> IIUC, the regex is an acceptable defense because it's unlikely that you can form random garbage to match that regex.

I don't think this is true. You can form random garbage (in the signature domain), then hex-encode it and it *will* match the regex.

**Comment by haydentherapper** [comment]
I don't know enough of the math side of this, but can you pick random garbage of a specific length? I thought it was probabilistically unlikely that you could find garbage of the right length. If not, then yea, we'll need to consider something else.

**Comment by haydentherapper** [comment]
Hrm, alrighty, we'll need to consider something else then. I'd like to at least add some warnings around the usage of WithDigest in the meantime.

**Comment by haydentherapper** [comment]
+1 to all of those drawbacks. To search, you'd need to search by both the artifact's hash and hash-hash.

**Comment by znewman01** [comment]
As I think about it more, the fundamental issue is that pre-hashing for ECDSA (as we do for HashedRekords) is not really a correct thing to do. So I think your warning for `WithDigest` is a good idea.

You *could* make the canonical strategy "sign the *hash* of the artifact, not the artifact" (which implicitly double-hashes). This would fix the Rekord/HashedRekord incompatibility. Call me weird but I actually kind of like this (thought it'd be a pretty huge effort to cut over)

**Comment by haydentherapper** [comment]
One option is another type, HashedHashedRekord (I'm not good at naming, Hashed^2Rekord), but we'd need to maintain HashedRekord indefinitely, or at least until we phase out a log shard that contains HashedRekord records. My only concern is how to clearly explain this to clients.
