### ISSUE TITLE
Hashivault KMS provider public key vs. verify

### ISSUE THREAD

**Issue by dlorenc** [sigstore/sigstore#48]
There's an issue with the hashivault provider that I haven't quite been able to pin down yet. I noticed it while testing https://github.com/sigstore/cosign/pull/278, so the bug may not actually be here.

The existing PR works when you sign/verify with the provider API itself, but does not work when you verify against the exported public key. That is:

`cosign sign -key hashivault://foo` followed by `cosign verify -key hashivault://foo` works

but

`cosign sign -key hashivault://foo` followed by `cosign public-key -key hashivault://foo > hk.pub && cosign verify -key hk.pub` does not work.

**Comment by dlorenc** [comment]
cc @RichiCoder1

**Comment by RichiCoder1** [comment]
Hmm. Looking into the implementation of `cosign public-key`, it looks like it calls https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/public_key.go#L101 which in turns calls https://github.com/sigstore/cosign/blob/8d77b5f1149a209bb34f5509dd1a1299c9439f2d/cmd/cosign/cli/keys.go#L40 and appears to still have a hard coded reference to gcpkms.

**Comment by dlorenc** [comment]
Ah, actually I got that one as part of the PR :)
https://github.com/sigstore/cosign/pull/278/files#diff-cebf999069fbd27117b60741df471df8bd8ebbbebcc80d085c21959bc813a1d4

**Comment by RichiCoder1** [comment]
My bad! Let me keep digging, maybe I'm not outputting the key correctly.

**Comment by dlorenc** [comment]
The key looked right, my guess is that it has to do with the hmac... The data being signed must be hashed slightly different.

**Comment by RichiCoder1** [comment]
I think you were right about HMAC: Did a PR which swaps `vault` hmac for local sha and swaps e2e test to use the same verifier as `cosign verify` and it seems to be happy now: https://github.com/sigstore/sigstore/pull/49

**Comment by dlorenc** [comment]
Thanks!
