### ISSUE TITLE
Race condition in flow_test

### ISSUE THREAD

**Issue by dlorenc** [sigstore/sigstore#50]
Unrelated: It looks like pkg/oauthflow/flow_test.go is experiencing a race condition

From: https://github.com/sigstore/sigstore/pull/49

**Comment by lukehinds** [comment]
Hey, took a look at #49 , but I can't see any details on the race condition @RichiCoder1 do you have any guidance on how to recreate this?

**Comment by RichiCoder1** [comment]
It was just happening randomnly when I was running the test suite repeatedly while work on an unrelated tests on a partially loaded machine.

**Comment by lukehinds** [comment]
going to close now, please do reopen if witnessed again
