### ISSUE TITLE
Support multiple instances of sigstore.

### ISSUE THREAD

**Issue by vaikas** [sigstore/sigstore#544]
**Description**

Some background here:
https://github.com/sigstore/scaffolding/issues/211

Currently, when testing with scaffolding, we create some env variables. It would be preferable to remove env variables and to utilize tuf roots as public sigstore instance uses. However, as part of that work, we should also ensure that things like policy-controller can be configured to validate images against multiple sigstore instances (for example, a private one as well as a public one). So this is tracking support for that.
@asraa

**Comment by haydentherapper** [comment]
@vaikas what were the AIs left for this?

**Comment by vaikas** [comment]
scaffolding has been supporting this for awhile now, and also policy-controller, so I will close this
https://docs.sigstore.dev/policy-controller/overview/#support-for-multiple-or-custom-sigstore-instances

Thanks for the cleanups!
