### ISSUE TITLE
TUF: Sigstore TUF clients trust any delegation for sigstore custom usage

### ISSUE THREAD

**Issue by asraa** [sigstore/sigstore#562]
**Description**

TUF delegations are delegated certain PATHS. in sigstore, we consume targets via custom metadata, not paths. therefore, if we have a delegation, that delegated key can sign off on any custom metadata, and that will be consumed by clients for rekor/fulcio usage.

 i.e. we currently cannot say the rekor delegation should only sign for targets tagged with **rekor** custom metadata. right now, rekor delegation could add a target that should be for **fulcio** usage.

immediate fix:
* sigstore tuf clients should only trust top-level targets for custom metadata.

long-term fix:
* figure out how to delegate usage to role delegations.

@kommendorkapten when you have a chance to read through TUF spec, would love thoughts on this.

@haydentherapper 

**Version**

**Comment by haydentherapper** [comment]
@asraa Should we remove all delegation code from the TUF Sigstore client until we add back delegations to the metadata?

**Comment by haydentherapper** [comment]
@asraa this good to close?

**Comment by asraa** [comment]
This is closed now - our delegations in sigstore/root-signing are now enforced to have paths that follow under the delegation name and do not conflict with our top-level targets - and that being said, we now only have one spec compliant top level target, the trusted_root.json
