### ISSUE TITLE
Clarify what is sent to rekor

### ISSUE THREAD

**Issue by letmaik** [sigstore/sigstore#59]
Is it always a metadata document that is constructed by the sigstore client as seen on https://sigstore.dev/what_is_sigstore/? The current code seems to send the whole input file to rekor if I'm not mistaken (just by looking at `cmd/sign.go`).

**Comment by bobcallaway** [comment]
The entire file is sent to rekor so that the signature can be verified as a prerequisite of making a new entry into the tlog. The contents of file is not entered into the tlog - only the signature, digest, and public key.

**Comment by letmaik** [comment]
I'm just looking at https://github.com/sigstore/rekor/pull/314. Is that also the case for in-toto attestations? I can't quite figure out all the data types but it looks like this stores the whole payload, right?

**Comment by bobcallaway** [comment]
I haven't done a thorough review of that PR yet, so I can't comment definitively. @dlorenc ?

**Comment by dlorenc** [comment]
> I haven't done a thorough review of that PR yet, so I can't comment definitively. @dlorenc ?

Nope, it should just be the hash again, but I might have messed things up.

Note though, I am working on a slightly longer term method to store the entire attestations for ITE-6. See here: https://docs.google.com/document/d/12JKXypgnDNQ2NBJYR73zLktSXj2pfBJcQWl675n_VdE/edit
