### ISSUE TITLE
Release 1.0 planning

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore#66]
- [x] implement improved e2e testing #46 
- [x] Allow the OOB authentication flow when we can't open a browser. #62
- [x] implement dog food signing / verification
- [ ] Update upstream projects who import / vendor from sigstore/sigstore

**Comment by cpanato** [comment]
@lukehinds I don't have permissions to create milestones, can you create that? or how we should proceed?

I'm checking if we can have some GH actions to add milestones for us, but looks like it will need some tokens to write in the repos. I was thinking to create a GitHub sigstore-bot user to help on the tasks

**Comment by lukehinds** [comment]
> @lukehinds I don't have permissions to create milestones, can you create that? or how we should proceed?
> 
> I'm checking if we can have some GH actions to add milestones for us, but looks like it will need some tokens to write in the repos. I was thinking to create a GitHub sigstore-bot user to help on the tasks

Sure, lets go for it. Let's connect on slack and get this setup.

**Comment by cpanato** [comment]
@lukehinds @dlorenc @bobcallaway What is your plan date to release sigstore 0.1.0? I would like to create the milestone to track the issues/prs and the planned date for the release.

I will create a milestone for now with no dates, but lets define a date

**Comment by lukehinds** [comment]
#28 is a little hard to timebox at present, as we are still working on the policy files with TUF. I would keep it open just for now.

**Comment by cpanato** [comment]
release is out https://github.com/sigstore/sigstore/releases/tag/v1.0.0
