### ISSUE TITLE
Fuzzing build looks broken

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore#682]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#sigstore

@naveensrinivasan Do you know why the build might be broken? Seems like it was working on the 7th.

**Comment by haydentherapper** [comment]
```
Step #3 - "compile-libfuzzer-address-x86_64": replacing *testing.F
Step #3 - "compile-libfuzzer-address-x86_64": # github.com/sigstore/sigstore/test/fuzz
Step #3 - "compile-libfuzzer-address-x86_64": ./fuzz_password_test.go_fuzz_.go:38:17: undefined: testingtypes.Errorf
Step #3 - "compile-libfuzzer-address-x86_64": ./fuzz_password_test.go_fuzz_.go:42:17: undefined: testingtypes.Errorf
Step #3 - "compile-libfuzzer-address-x86_64": 2022/09/11 06:12:36 failed to build packages:exit status 2
```

**Comment by haydentherapper** [comment]
https://github.com/AdamKorcz/go-118-fuzz-build/commit/5a8cbd76e69a3fec53b692fa51ee230ae79a72f8

Hey @AdamKorcz, it seems like this commit might have broken something. I'm not very familiar with Go fuzzing, do you know if there's something we need to change in our fuzzing test, or is there a bug in the linked commit?

**Comment by naveensrinivasan** [comment]
> https://oss-fuzz-build-logs.storage.googleapis.com/index.html#sigstore
> 
> @naveensrinivasan Do you know why the build might be broken? Seems like it was working on the 7th.

I can take on this. I will let @AdamKorcz let me know what needs to be done.

**Comment by AdamKorcz** [comment]
> [AdamKorcz/go-118-fuzz-build@5a8cbd7](https://github.com/AdamKorcz/go-118-fuzz-build/commit/5a8cbd76e69a3fec53b692fa51ee230ae79a72f8)
> 
> Hey @AdamKorcz, it seems like this commit might have broken something. I'm not very familiar with Go fuzzing, do you know if there's something we need to change in our fuzzing test, or is there a bug in the linked commit?

I think you are right. Reverting that should solve the issue. I think I have it covered later today.

**Comment by AdamKorcz** [comment]
Should be fixed with https://github.com/AdamKorcz/go-118-fuzz-build/commit/e1f97a00006b1720cec18bebee8ec0f2474e3426

**Comment by haydentherapper** [comment]
Thanks so much for the quick fix!
