### ISSUE TITLE
Sigstore as dependency

### ISSUE THREAD

**Issue by MarcosDY** [sigstore/sigstore#695]
**Question**

Hi there! I'm a maintainer on the SPIRE project, and have been reviewing a PR to add Sigstore validation support. One of the biggest challenges we have with the change is that we have to pull in three of your projects as a dependency in order to do the validation. The resulting go.sum change is well over 1k lines long.

We had a similar problem in SPIRE with regards to our users pulling in protos and libraries for interactions with SPIRE or plugin authoring. We ended up creating dedicated repo's with libs/sdk's that have a limited dependency tree and were easy to import - this seems to have solved the problem well.

Dependencies on [PR](https://github.com/spiffe/spire/pull/3159/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R59-R61):
```
github.com/sigstore/cosign v1.9.0
github.com/sigstore/rekor v0.4.1-0.20220114213500-23f583409af3
github.com/sigstore/sigstore v1.2.1-0.20220424143412-3d41663116d5
```

Are we doing something wrong here? Is there an easier way to import the libs we need for validation?

**Comment by znewman01** [comment]
You're not doing anything wrong; this is a limitation of the libraries as written currently. See discussion in https://github.com/sigstore/sigstore/issues/678

We hope to have a better story here soon.
