### ISSUE TITLE
add artifact hash 

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore#72]
It should be possible to also send the digest instead of the artifact itself.

**Comment by cpanato** [comment]
@lukehinds I would like to check this issue, but I'm a bit lost about where this change should be made, can you point or give a clarification? thanks!

**Comment by lukehinds** [comment]
sure, currently what we do is reference the file `--artifact`  and it hashes the blob and signs that hash, this instead would allow you to just pass the hash directly.

rekor-cli does something similar: https://github.com/sigstore/rekor/blob/dbbbff597bc250b276467892d3d05d6179dc5ace/cmd/rekor-cli/app/pflags.go#L54

While I think about it, handling urls might be useful as well (download and hash)

@dlorenc / @bobcallaway any thoughts?

**Comment by bobcallaway** [comment]
@lukehinds given that we've removed the CLI from s/s, is this issue moot?

**Comment by lukehinds** [comment]
It is yes!
