### ISSUE TITLE
Improve the "Sigstore Auth Successful" page

### ISSUE THREAD

**Issue by imjasonh** [sigstore/sigstore#732]
Today, the post-OAuth page that gets displayed by tools like `cosign`, `gitsign` etc, is pretty ...sparse.

<img width="391" alt="Screen Shot 2022-10-10 at 8 55 26 AM" src="https://user-images.githubusercontent.com/210737/194871146-0b9e9e92-8a63-4f2e-bdf8-99ae549818b2.png">

That's not necessarily a bad thing. Being sparse also means it's not very resource intensive. It doesn't make any external requests to load CSS/JS/fonts/etc., and as the default for clients that may not have access to the public internet, that's a good thing.

At the same time, regular users of sigstore clients often end up with tons of these windows open (e.g., from `gitsign` and a long rebase chain, without the credential cache running).

For context, the source of that page is here:

https://github.com/sigstore/sigstore/blob/a862909dae84e62c1ac0eb356f311a73a62c0a1a/pkg/oauth/interactive.go#L18

## Closing the window 

We've learned (e.g., #484) that the page can't be closed using JavaScript. Windows can only reliably close windows that they themselves opened, and in our case the window was opened by `cosign` etc. We arrive at this page after some redirects through the OAuth flow.

This means that:
- the page can't autoclose after some wait
- the page can't include a button or click target that closes the window

If you try, you get `Scripts may close only the windows that were opened by them.`

To save you (and future-me) time, the StackOverflow results for that message include lots of obsolete hacks that browsers now block.

So closing the window is probably not feasible. Instead, we can at least make the page more _useful_.

## Making the page useful

New users are confronted with this page immediately after selecting their OAuth provider of choice. It's not really clear why you're here, what's happening, what to do next, etc. Close the window, sure, but then what?

We _don't_ have much context to make this page more specifically helpful to the user. The page URL is something like `http://localhost:59640/auth/callback?code=qdvscillhxxxxxxncrlbxhmtyg&state=2Fwdxxxx47dER2tw3I0ElvIgvxxx` -- there's (purposefully, I think) no information about what user just authed. At the point in the flow where this page is opened, Fulcio hasn't been contacted yet, so there's no information about the cert it returned. There's no Rekor entry yet to link to.

I think we can at least provide more text about what's happening, and where to go to learn more. A link to some page on docs.sigstore.dev describing the OAuth flow a bit better maybe, or a brief description of what just happened, what's happening now, etc.

The page contents are configurable by clients, so `cosign` could include text like "go back to the terminal where you invoked `cosign` to see more". Sigstore's own tools should at least aim to make these pages look and act consistently with each other.

## Making the page prettier

While (/if) we're adding content to read, we should also consider making the page easier to read. Nothing against black 12pt Times New Roman, but we've discovered over the last 20 years it may not be the best thing to read on a screen.

A few lines of CSS could go a long way to improving the experience.

## Considerations

The page shouldn't load any _external_ resources (e.g., JS/CSS/fonts) from the internet. Since `cosign`/`gitsign` are general-purpose clients, we can't guarantee clients have access to these resources at all. Even if they do, clients may not want to communicate to those external services that they're using these tools, and how or when.

This constraint should also help us avoid making the page _too_ flashy -- if we have to bundle everything into the page we're probably not going to make it some monstrous 15 MB dynamic-loading single-page app either.

---

This is mainly an issue to collect ideas and previous findings. If there's something you've ever wanted to see from the auth-success page, please tell us!

cc @wlynch @znewman01

**Comment by Havoc24k** [comment]
I would really like to be able to set my own HTML template that I could configure per installation and override the default one. 

I think right now this is a constant set on `sigstore/pkg/oauth/interactive.go`, we could override that by loading either a static `.html` file or a `.tmpl` template file with a context object.

**Comment by imjasonh** [comment]
The HTML is defined in a const that's compiled into the client tool (e.g., `cosign`), and not configurable from the Fulcio installation for example.

I was _about_ to say that you could theoretically update this value at `cosign`-compile-time by abusing `ldflags`, but it looks like that's not actually possible either:

I tried this:
```
go build -ldflags="-X 'github.com/sigstore/sigstore/pkg/oauth/interactive.InteractiveSuccessHTML=\"<body onload=alert() />\"'" ./cmd/cosign/
```

And the previous const still showed up.

Digging through the binary it looks like there's no symbol for the const:

```
go tool nm ./cosign | grep Interactive
10151b840 T github.com/sigstore/sigstore/pkg/oauthflow.(*InteractiveIDTokenGetter).GetIDToken
10151c3c0 T github.com/sigstore/sigstore/pkg/oauthflow.(*InteractiveIDTokenGetter).GetIDToken.func1
10151c440 T github.com/sigstore/sigstore/pkg/oauthflow.(*InteractiveIDTokenGetter).GetIDToken.func1.1
10151c6f0 T github.com/sigstore/sigstore/pkg/oauthflow.(*InteractiveIDTokenGetter).GetInput
10151c720 T github.com/sigstore/sigstore/pkg/oauthflow.(*InteractiveIDTokenGetter).GetOutput
10151c490 T github.com/sigstore/sigstore/pkg/oauthflow.(*InteractiveIDTokenGetter).doOobFlow
1025c9700 R go.itab.*github.com/sigstore/sigstore/pkg/oauthflow.InteractiveIDTokenGetter,github.com/sigstore/sigstore/pkg/oauthflow.TokenGetter
1010c5d10 T k8s.io/client-go/plugin/pkg/client/auth/exec.isInteractive
```

(I found these instructions [here](https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications))

This may indicate that the const is inlined before ldflags comes into play.

If this seems useful (sounds like we think it is) then we can probably do something with [`//go:embed`](https://pkg.go.dev/embed) to allow tool builders to compile in their own HTML more easily.

(Tools can also always change this by modifying source code, but HTML inside Go is only a little better than HTML-inside-Go-modified-by-ldflags 🤮  -- we can do better.)

**Comment by julienv3** [comment]
Thoughts on a revamp of the static html as follows (100% offline)?
![image](https://user-images.githubusercontent.com/18708970/208170763-d7a903aa-87a8-4526-baa9-fd9416c53c83.png)
(For context, modelled after the following)
![image](https://user-images.githubusercontent.com/18708970/208170792-f2c58643-63ce-41fd-bacd-5981267bd0c0.png)

**Comment by haydentherapper** [comment]
That looks really nice!

**Comment by imjasonh** [comment]
I wrote a Chrome extension to automatically close the windows: https://github.com/imjasonh/chrome-sigstore

It's not yet published to the webstore, but based on a couple days' dogfooding it works well enough. If you want to try it out (very alpha, no warranty etc) please leave any feedback on that repo.

**Comment by imjasonh** [comment]
This is now published to the webstore, in case you want to install it without twiddling developer bits: https://chrome.google.com/webstore/detail/sigstore-close-post-auth/incpcifganmpehaiplhjlfphaflbkdoj

Tell your friends! Hide it from your enemies!!
