### ISSUE TITLE
[feature requirement] Add support for openPGP?

### ISSUE THREAD

**Issue by TommyLike** [sigstore/sigstore#791]
**Description**

Will openPGP be supported in sigstore？including keys management and signing/verifyication?

**Comment by lukehinds** [comment]
PGP is supported in rekor, as in you can store a digest, public key and signature there.

We don't have support for creating keys / sigs with PGP. What is the use case you're interested in and any reason why a more modern protocol like ecdsa might not fulfil your needs?

**Comment by TommyLike** [comment]
> PGP is supported in rekor, as in you can store a digest, public key and signature there.
> 
> We don't have support for creating keys / sigs with PGP. What is the use case you're interested in and any reason why a more modern protocol like ecdsa might not fulfil your needs?

In order to sign rpm packages within cosign and sigstore packages.

**Comment by TommyLike** [comment]
@lukehinds is there anyway to achive this?

**Comment by lukehinds** [comment]
@TommyLike 

There is an RPM type in rekor: https://github.com/sigstore/rekor/tree/main/pkg/types

As far as signing rpm packages, this might be a little out of scope for us as its not just implementing GPG, you will need to work with RPM headers as well, which is where the signature is stored.

what you could do, is follow something like this: https://access.redhat.com/articles/3359321

You can then just send the signed RPM to rekor, which will store it?

**Comment by lukehinds** [comment]
p.s. cosign is not likely a good tool to use, unless you want to store the RPMs into a container registry?

**Comment by TommyLike** [comment]
@lukehinds ok, we could handle the rpm metadata and signing & verification ourself, what if sigstore library can provide a common ability to manage the openPGP keys?

**Comment by lukehinds** [comment]
@TommyLike may I ask intended use case or the community where you want to implement this. We could maybe look at alternatives for you first. [PGP is a bit of flawed protocol](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html) and might limit you if ever want to explore further key management approaches (such as fulcio based keyless signing)?

**Comment by lukehinds** [comment]
technically we could, but I am just not convinced it's a good idea. we would only be able to cover key generation here, and not create a signer interface as it requires a specific approach for RPM.

I would recommend just using the protonmail library which has a nice key generation interface: https://github.com/ProtonMail/gopenpgp#generate-key - This is likely all we would do, but you will end up with a smaller binary as you won't be pulling in everything under sigstore/sigstore then

**Comment by TommyLike** [comment]
> technically we could, but I am just not convinced it's a good idea. we would only be able to cover key generation here, and not create a signer interface as it requires a specific approach for RPM.
> 
> I would recommend just using the protonmail library which has a nice key generation interface: https://github.com/ProtonMail/gopenpgp#generate-key - This is likely all we would do, but you will end up with a smaller binary as you won't be pulling in everything under sigstore/sigstore then

@lukehinds  Hmm, not only the key generation, since openPGP also support detached signature, it can be supported in sigstore? But also, I have a question that for most of the KMS plugins, it looks like the the openPGP is not on their support list?

**Comment by lukehinds** [comment]
I am not against it per-say, if its implemented well with decent unit / integration testing. But overall for general signing, we have tried to steer folks away from PGP, as its [considered broken at best](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html). I would say if you want detached sigs, use a more modern protocol (ecdsa etc).

**Comment by TommyLike** [comment]
Thanks @haydentherapper @lukehinds I will look into this, the reason that we are requesting openPGP is it's official supported in RPM packages now: https://rpm-software-management.github.io/rpm/manual/signatures_digests.html

**Comment by haydentherapper** [comment]
There’s a lot of discussion about pgp in the Rekor repo. If you have any requests, take a look there. We won’t add support for working with pgp in the core library.
