### ISSUE TITLE
Any plans to add a verification API for keyless signatures?

### ISSUE THREAD

**Issue by wata727** [sigstore/sigstore#812]
**Question**

Any plans to add a verification API for keyless signatures?

First, let me share some background on this question. I'm a maintainer of a project called [TFLint](https://github.com/terraform-linters/tflint). Without going into details, the CLI has a plugin system and the ability to install any binary from GitHub releases as a plugin. At this time, a PGP signature is verified to prevent unauthorized binaries from being installed.
https://github.com/terraform-linters/tflint/blob/v0.42.2/plugin/signature.go

As you can imagine, there are key maintenance issues. Unfortunately, third-party developers must manage own PGP keys to distribute their plugins. So, I'm excited about the idea of keyless signing as a way to address this issue. I believe that you can verify the plugin binary using cosign as follows:

```
cosign verify-blob --certificate checksums.txt.pem --signature checksums.txt.keyless.sig --certificate-github-workflow-repository=terraform-linters/tflint-ruleset-aws checksums.txt
sha256sum --ignore-missing -c checksums.txt
```

NOTE: The `checksum.txt.pem` and `checksum.txt.keyless.sig` is created with [this settings](https://github.com/terraform-linters/tflint-ruleset-aws/blob/v0.19.0/.goreleaser.yml#L25-L37).

The request here is to verify keyless signatures as a feature of TFLint without using cosign. I understand that sigstore/sigstore is a library that provides such features, but please let me know if there is any misunderstanding. I hope that the methods around [here](https://github.com/sigstore/cosign/blob/v1.13.1/cmd/cosign/cli/verify/verify_blob.go#L149-L161) will be provided as a Go API.

Finally, thank you for working on this great project.

**Comment by haydentherapper** [comment]
We've begun work on [sigstore-go](https://github.com/sigstore/sigstore-go), and we'll be moving the verification logic out of Cosign into this library.

**Comment by wata727** [comment]
Nice, in the future I will consider using sigstore-go. Thank you.
