### ISSUE TITLE
Remove operational client code, respin as just a client library. 

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore#89]
We are starting to run into some pains from circular dependencies (rekor inherits from sigstore/sigstore and in turn sigstore/store inherits from rekors-cli). In light of the fact this code base is not gaining traction as a client, and is becoming more widely utilized as a client library, all code such as sign / verify should be removed and refactored as /examples.

We should also better document how to use this library for those who wish to build clients, making it a lite SDK. Tests should also be improved and narrowed on this being a library only.

In turn this should make releases more stable for those consuming this as a client library (as we won't have client specific features being proposed).

**Comment by dlorenc** [comment]
cc @dekkagaijin

**Comment by dekkagaijin** [comment]
Fixed in https://github.com/sigstore/sigstore/pull/90 and https://github.com/sigstore/sigstore/pull/91
