### ISSUE TITLE
Proposal: Add Jake Sanders to the maintainers list!

### ISSUE THREAD

**Issue by dlorenc** [sigstore/sigstore#97]
**Description**
He's the #2 contributor to this repository, and has implemented a large amount of refactoring and feature work. We should add him as a maintainer!

The CODEOWNERS file here just maps to a team though, so let's track the decision here and then manually add on GitHub.

**Comment by lukehinds** [comment]
+1 , Jake has done some solid work.

**Comment by cpanato** [comment]
+1

**Comment by bobcallaway** [comment]
+1, congrats @dekkagaijin 

added to sigstore/sigstore-codeowners

**Comment by dekkagaijin** [comment]
Thanks, all :)
